### ISSUE TITLE
Tidspunkt for "save"

### ISSUE THREAD

**Issue by stave1989** [erlendsellie/priceanalyzer#17]
Jeg stusset litt over perioden for "save" når jeg benytter Priceanalyzer for å styre varmekabler. 
Som du ser ut av bildet er perioden for "save" plassert til høyre for pristoppen, og ikke sentrert over toppen for å dekke de dyreste timene. Er det en grunn til dette? 
![image](https://user-images.githubusercontent.com/57415182/205925365-1473a1fe-57fe-4177-9ea6-e52c00d8fda7.png)

**Comment by erlendsellie** [comment]
Heisann!
Her mangler PriceAnalyzer rett og slett litt dokumentasjon på hvordan den fungerer, men jeg skal prøve å forklare hva PriceAnalzyer tenker her, før jeg får på plass skikkelig dokumentasjon:

**Hvordan fungerer algoritmen sånn ca?**
PriceAnalyzer's save er ikke basert på 'topper', og 'boost' er ikke basert på bunner. 
De er basert på **om prisen kommer til å gå vesentlig opp eller ned, i løpet av de neste timene**.
Når PriceAnalyzer regner ut når den skal booste, og når den skal save, så ser den noen timer inn i fremtiden, og sjekker om prisen i fremtiden er på vei til å gå skikkelig ned, eller skikkelig opp, basert på dagens topp og bunn. Jeg tror jeg skrev at den må gå ned rundt 20% i løpet av 3 timer, for at den skal save, ellernoesånt. 
Om den ser at prisen da faller en del, så ser den muligheten til å kunne flytte forbruket noen timer, til billigere timer. Når den ser at prisen går opp en del snart, så booster den for å prøve å varme opp rett før prisøkningen kommer. 
Så, klokken 20:00 på den aktuelle timen, som er relativt dyr, så ser ikke PriceAnalyzer noen 'bedre tider' i løpet av de 3 neste timene, og vil dermed ikke kjøre 'save'. 

Klokken 21:00 er max-timen for dagen, og da kjører den alltid 'save'.
Den begynner først senere på dagen å se at prisen faller skikkelig, og vil da kjøre 'save'.

Om jeg legger inn at den skal se flere enn 3 timer inn i fremtiden, får vi plutselig mange flere timer med 'save', og det vil i større grad gå ut over komforten. Det hadde passet for dagens pris-kurve, men ikke nødvendigvis for gårsdagens. De dagene prisen bare synker og synker, så ville man kunne fått 'save'-timer hele dagen, og det er heller ikke optimalt.

**Hvorfor plukker ikke den bare ut de dyreste timene og 'saver' da?**
Jeg skulle gjerne ønske at den hadde tatt med klokken 20:00 i dag selv, da det er en dyr time. Men å 'plukke ut toppene' er ikke så enkelt. En topp er greit definert i dagens pris i skjermbildet, men prisene vi har sett de siste par dagene har hatt priskurver der hele dagen har hatt en stabil, høy pris, mens nattene har vært litt rimeligere. Da er det vanskelig å plukke ut hva som er typiske 'topper', og hva som er en normal pris. Jeg har forsøkt dette, men har da sett dager hvor alle timene mellom 0800-2000 har blitt 'save', da prisen har vært stabil høy gjennom hele dagen.

Om du, eller noen har et forslag på hvordan dette kan plukkes ut, så tar jeg gjerne imot forbedringsforslag. 
Når jeg skrev dette, så kom jeg på et forslag, som jeg kan teste ut: **Plukk ut de tre dyreste timene i løpet av en dag, og kjør 'save' på dem.**
Det ville løst dagens pristopp, men kanskje ikke andre dager. 

Beklager et laaangt svar her, men håper det oppklarer hvordan den oppfører seg, og hvorfor klokken 20:00 i dag ikke er en 'save'-time :-)
