### ISSUE TITLE
Some more setpoints

### ISSUE THREAD

**Issue by alekslyse** [erlendsellie/priceanalyzer#22]
Would it be possible with two things; Im trying to make a pretty dashboard for this integration that stands up to the apps in their cellphone, so people can use Vibb and others that charge for that function (then you dont need it, if everything comes from this app).

Could it be possible to have -24h, today and +24h?

Could pr day it be an attribute of max and min for that day?

**Comment by erlendsellie** [comment]
Could you move this to to the 'discussions' page, as it's not really an 'issue', but more like a feature request / idea?
 I think this can be solved with apex charts, without rewrites to the integration. Tomorrow's prices are already available through the integration, and yesterday's prices are also available through Home Assistant's history/recorder.

**Comment by erlendsellie** [comment]
PriceSensor with the current Price was added in the 1.2 release, which displays the current price, like the Nordpool-sensor.
Also added support for statistics with for all the sensors this integration provides.

I haven't had time to create this kind of chart in Apex Charts, but you may want to take a look at the brush-option, to be able to go forwards and backwards in time with a navigation-view.
