### ISSUE TITLE
Low price - not working

### ISSUE THREAD

**Issue by aherbjornsen** [erlendsellie/priceanalyzer#33]
I am struggling a bit to get "low price" to work.

I have configured Price analyzer like this:

![image](https://github.com/erlendsellie/priceanalyzer/assets/8121629/b21e2ab5-cb1a-446a-9710-6e26f77ee25f)

And with the current price (appx. 0.4 NOK) I was expecting to see my VVB sensor reporting the "low price" value (which I have set to 70). Instead it reports this:

![image](https://github.com/erlendsellie/priceanalyzer/assets/8121629/d3c14791-8fa3-4423-bd71-83b6dc7abdfd)

Is there something I have misunderstood or this a bug?

**Comment by erlendsellie** [comment]
Hei!
Tar dette på norsk jeg, siden jeg ser du er nordmann (other's who may see this as relevant can use google translate?)
Klarer du å se den samme timen i raw_today listen for sensoren? Der står det en 'reason' (forklaring) for hvorfor den gjør hva den gjør.

Om du i tillegg hadde lagt ut configen for VVB-sensoren (den siste som vises i bildet der), så kan jeg sannsynligvis forklare hva som skjer feil her.

**Comment by aherbjornsen** [comment]
Ok. Nytt forsøk..

Jeg har denne i konfig:

![image](https://github.com/erlendsellie/priceanalyzer/assets/8121629/7efb0515-37a8-433c-8348-bc9e302da5b6)

Hvor vvbsensor konfigurasjon er: 

`{"default_temp": 60, "five_most_expensive": 40, "is_falling": 50, "five_cheapest": 70, "ten_cheapest": 55, "low_price": 70, "not_cheap_not_expensive": 50, "min_price_for_day": 80}`

Akkurat nå sier den:

![image](https://github.com/erlendsellie/priceanalyzer/assets/8121629/9f595953-1c3d-4f8b-9dbf-47fc5ec3a0de)

og under raw_today for klokken 21:00-22:00

![image](https://github.com/erlendsellie/priceanalyzer/assets/8121629/c6eb3f40-446a-4813-a9a1-454fe454a82b)


Jeg trodde at low_price ville trumfe den vanlige justeringen, slik at jeg når det var billig strøm ville jeg kunne settte 70 grader uansett.

**Comment by aherbjornsen** [comment]
Glemte å ta med denne fra selve priceanalyzer-sensoren, under raw_today:

![image](https://github.com/erlendsellie/priceanalyzer/assets/8121629/8de00453-2666-474a-89ad-d1d7056e810f)

Skulle ikke "low_price" være true her?

**Comment by erlendsellie** [comment]
'Low Price' eller lav pris, er en litt variabel sak, som er "arvet" fra når denne integrasjonen brøt ut fra Nordpool-integrasjonen. Den blir kalkulert ut i fra gjennomsnittsprisen på en dag, og har 0.9(i ditt tilfelle), som den gjør følgende kalkulering med for å finne ut om det er lav pris:
```
            price (pris denne timen) < self._average (gjennomsnittspris for dagen) * self._low_price_cutoff (0.9 i ditt tilfelle)
```

Om 'Low Price cutoff' hadde vært satt til 1, så hadde lav pris vært alt under gjennomsnittpris. I ditt tilfelle er det  noe lavere.

De 5 billigste timene og de 10 billigste timene er sannsynligvis billigere, og trumfer 'low price'.
De har følgende prioritert:

1. min_price_for_day
2. five_most_expensive
3. five_cheapest
4. ten_cheapest
5. is_falling
6. low_price

'Is falling' vil si at prisen blir betraktelig billigere(relativt) om en time eller to.
Selv har jeg denne configen nå. Tallene er litt rare for å enkelt kunne se hvilken config som er aktiv, men den kan vise litt hva som er tiltenkt. Merk at temperaturen man burde kjøre kommer an på varmtvannstank og hvor ofte og mange som dusjer.

```
{
   "default_temp": 70,
   "five_cheapest": 70,
   "five_most_expensive": 40,
   "is_falling": 48,
   "low_price": 50,
   "min_price_for_day": 80,
   "not_cheap_not_expensive": 49,
   "ten_cheapest": 51
}
```

Håper dette var oppklarende.
Jeg burde skrive litt mer dokumentasjon rundt integrasjonen, men der har jeg rett og slett vært for lat. Rop ut om du har flere spørsmål, om du ikke synes det henger helt sammen enda, eller tror noe er feil :-)

**Comment by aherbjornsen** [comment]
Takk for grundig svar, da skjønner jeg.

Jeg tenkte at dette var gjort mot timespris og at jeg kunne sette en minstepris, og så varme opp uansett dersom strømmen var billig nok.
Men jeg har allerede en template sensor wrappet utenpå sensoren fra Priceanalyzer (for å styre ferier og litt annet), så det er enkelt å legge det inn der i stedet.

**Comment by erlendsellie** [comment]
Aha.
Det styres jo mot timespris, men attributtene det kontrolleres mot er jo relativ opp mot hele dagens timespriser.
For maks besparelse, så vil jeg uansett anbefale å heller styre mot billigste 5 timer, eller billigste 10 timer, da en fast minstepris ikke trenger å slå inn i løpet av en dag.

Men man ser jo best selv hva som passer for seg selv :-)
Her er et bilde som illustrerer når de 5 billigste, 10 billigste og 5 dyreste er aktive i dag, i trøndelag:

![image](https://github.com/erlendsellie/priceanalyzer/assets/18458417/95f867f0-f456-4fff-a35b-ee0dbcc4e542)

**Comment by Roos-AID** [comment]
Please add summary of above in English... My norwegian is not that fluent.

**Comment by erlendsellie** [comment]
> Please add summary of above in English... My norwegian is not that fluent.

Hi!
Sorry about the late reply.
Here's a translation of the explanation for the low price attribute, and how the hot water sensor works "internally". Hope it helps, and if there's any doubt, i can explain some more:-)


'Low Price' or 'lav pris' (low price in Norwegian) is a somewhat variable matter, inherited from when this integration broke away from the Nordpool integration. It is calculated based on the average price of a day and has 0.9 (in your case) as its factor. It performs the following calculation to determine if it is a low price:

\[ \text{{price (price this hour) < self._average (average price for the day) * self._low_price_cutoff (0.9 in your case)}} \]

If 'Low Price cutoff' had been set to 1, then low price would have been anything below the average price. In your case, it's slightly lower.

The 5 cheapest hours and the 10 cheapest hours are likely to be cheaper and override 'low price'. They have the following priorities:

- min_price_for_day
- five_most_expensive
- five_cheapest
- ten_cheapest
- is_falling
- low_price

'Is falling' means that the price will become considerably cheaper (relatively) in an hour or two.

Here's the current configuration. The numbers are a bit odd to easily see which config is active, but it can give an idea of the intention. Note that the temperature one should run depends on the hot water tank and how often and how many people shower.

```json
{
   "default_temp": 70,
   "five_cheapest": 70,
   "five_most_expensive": 40,
   "is_falling": 48,
   "low_price": 50,
   "min_price_for_day": 80,
   "not_cheap_not_expensive": 49,
   "ten_cheapest": 51
}
```

I hope this clarifies. I should write more documentation around the integration, but I've simply been too lazy. Feel free to reach out if you have more questions or if things still don't quite add up, or if you think something is wrong :-)
