### ISSUE TITLE
Error - PA is not working

### ISSUE THREAD

**Issue by espmas** [erlendsellie/priceanalyzer#38]
-->

## Version of the custom_component
Latest

## Homeassistant version
Latest

## Configuration

```yaml

Add your logs here.

```

## Debug log

_report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'priceanalyzer' calls async_write_ha_state from a thread at custom_components/priceanalyzer/sensor.py, line 403: self.async_write_ha_state(). Please report it to the author of the 'priceanalyzer' custom integration.

`

**Comment by erlendsellie** [comment]
Try the latest beta.

**Comment by espmas** [comment]
Thanks! Beta 1.5.3 worked! 

For this error for recorder: (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.priceanalyzer_kr_sand exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2024-05-18 09:40:10.523 WARNING

**Comment by erlendsellie** [comment]
Yup, that's a warning from Home Assistant. You can basically ignore it, but I've not found a solution for it. The only way I know how to fix it is to reduce the number of attributes on the sensor, eg, removing functions for the integration..
