### ISSUE TITLE
Price analyzer is not working

### ISSUE THREAD

**Issue by rinowit** [erlendsellie/priceanalyzer#39]
Hello, has the Priceanalyzer been discontiniued? When I updated the HA I just get that the sensor is not provided

![image](https://github.com/erlendsellie/priceanalyzer/assets/67904307/ff4d4509-8e75-471f-bad1-f25b228f0b3b)

**Comment by erlendsellie** [comment]
Hi,
Priceanalyzer should work.. Can you see anything in the logs?
I don't have time to further develop this integration at this time, unfortunately, but i should be able to solve critical bugs.

**Comment by rinowit** [comment]
It's undertandable:) I will check it up

**Comment by rinowit** [comment]
I just rolled back to the december version :)

**Comment by erlendsellie** [comment]
Ahh, the non-beta? If you had troubles with the beta, you can try to click "configure" and save again, and see if it works then.

**Comment by rinowit** [comment]
Update!
Lates beta is working fine. I was using 1.4 earlyer.

Thanks for helping
