### ISSUE TITLE
PriceAnalyzer stopped after nordpool update to 0.0.15

### ISSUE THREAD

**Issue by roddyduus** [erlendsellie/priceanalyzer#41]
## Configuration

```yaml

Add your logs here.

Logger: homeassistant.components.sensor
Kilde: helpers/entity_platform.py:909
integrasjon: Sensor (dokumentasjon, problemer)
Førs oppstått: 21:50:58 (4 hendelser)
Sist logget: 21:52:23

Error adding entity sensor.priceanalyzer_se1 for domain sensor with platform priceanalyzer
Error adding entity sensor.priceanalyzer_bergen for domain sensor with platform priceanalyzer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1365, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/priceanalyzer/sensor.py", line 367, in async_added_to_hass
    await self._data.check_stuff()
  File "/config/custom_components/priceanalyzer/data.py", line 1018, in check_stuff
    tomorrow = await self.api.tomorrow(self._area, self._currency)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/priceanalyzer/__init__.py", line 134, in tomorrow
    res = await self._someday(area, currency, "tomorrow")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/priceanalyzer/__init__.py", line 110, in _someday
    await self.update_today(None)
  File "/config/custom_components/priceanalyzer/__init__.py", line 91, in update_today
    await self._update("today")
  File "/config/custom_components/priceanalyzer/__init__.py", line 81, in _update
    data = await spot.hourly(end_date=dt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/priceanalyzer/aio_price.py", line 255, in hourly
    return await self.fetch(self.HOURLY, end_date, areas)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/priceanalyzer/aio_price.py", line 248, in fetch
    res = await asyncio.gather(*jobs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/priceanalyzer/aio_price.py", line 165, in _fetch_json
    return await self._io(
           ^^^^^^^^^^^^^^^
  File "/config/custom_components/priceanalyzer/aio_price.py", line 154, in _io
    return await resp.json()
           ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1243, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 404, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://www.nordpoolgroup.com/api/marketdata/page/10?currency=NOK&endDate=13-10-2024'
```

## Debug log

```text

Add your logs here.

```

**Comment by dlysnes** [comment]
This also applies to previous versions of Nordpool. It looks like Nordpool API has changed.

**Comment by roddyduus** [comment]
Nordpool does after the update show region, no1, no2, no3, no4 and no5 and not Bergen, Kristiansand, Oslo etc

**Comment by dlysnes** [comment]
Indeed:
https://github.com/custom-components/nordpool/pull/413

**Comment by roddyduus** [comment]
Will there come an updated version?

**Comment by dlysnes** [comment]
@erlendsellie has never let us down, and I trust the very good man will merge in the Nordpool updates soon :)

**Comment by erlendsellie** [comment]
Hi!
The last year has been quite busy and exhausting for me, so i have not been able to work on this integration.
This breaking change from the Nordpool API can be fixed two ways;

By merging 2 years of PR's from Nordpool, which will be really hard, as the code base for this integration is quite different.
Or;
Creating a new integration architecture, which uses the nordpool sensor from Home Assistant, and just crunching the price-saver numbers afterwards..

I'm leaning towards the latter. I don't have much time to work on this, but i'll try to get something up as soon as i can.

If anyone want's to help with the development of this integration, contact me

**Comment by NicklasAndersson** [comment]
The second option seems easier. I would like to contribute if I can. I have never built an integration for HA but I do work as a software dev.

**Comment by roddyduus** [comment]
For me is it enough having the posssibility to control automations by high price, normal price and low price. Do you eventually know about other integrations that can do that?

**Comment by erlendsellie** [comment]
> For me is it enough having the posssibility to control automations by high price, normal price and low price. Do you eventually know about other integrations that can do that?

I'll se if i can create a template sensor in home assistant that can be used in the mean time, using nordpool's sensor. Like -1 if high price, 0 if medium and +1 if low price? That's not quite how PriceAnalyzer works, but can be used in pinch while waiting for a new release.

**Comment by roddyduus** [comment]
Hi. I have started to test the integration nordpool planner.

**Comment by dlysnes** [comment]
Powersaver also has a heat-capacitor node (https://powersaver.no/nodes/ps-strategy-heat-capacitor.html), however not as good, easy setup and flexible as Priceanalyzer. I'm using powersaver for VVB and some other consumers, but a node pr thermostat with all the setup in powersaver requires a lot of overhead compared to easy blueprint.

**Comment by erlendsellie** [comment]
Hi @roddyduus .
Why did you close this issue?

**Comment by dlysnes** [comment]
@erlendsellie , maybe look to nordpool planner and see how it's fetching nordpool data there?

**Comment by roddyduus** [comment]
> Hi @roddyduus . Why did you close this issue?

Sorry. I just close it, as I did not "have an issue" anymore. As I have started to use a different integration.

**Comment by erlendsellie** [comment]
> > Hi @roddyduus . Why did you close this issue?
> 
> Sorry. I just close it, as I did not "have an issue" anymore. As I have started to use a different integration.

Ah, i understand. That's not how Github works though.
Thanks for raising this issue, anyway :-)

**Comment by erlendsellie** [comment]
> @erlendsellie , maybe look to nordpool planner and see how it's fetching nordpool data there?

Well, yeah. But the codebase between these integrations and nordpool is very different now, so it's not a simple job. I'm using this 
(https://github.com/erlendsellie/priceanalyzerv2/ )repo to write new code for this integration right now.

With the new integration, it will require a nordpool sensor to use as a base. This way, Priceanalyzer won't have to fetch the data from Nordpool by itself, and will work as long as Nordpool works.

**Comment by erlendsellie** [comment]
Fixed in the 2.0-BETA, will release a new version if this does not crash for anybody today.

**Comment by dlysnes** [comment]
> Fixed in the 2.0-BETA, will release a new version if this does not crash for anybody today.

Fantastic! Already installed and working smoothly on NO2, HA version 2024.11.3

Thanx a bunch, Erlend!

**Comment by erlendsellie** [comment]
Thanks for the feedback, @dlysnes!

Sorry it took so long to fix it.

**Comment by dlysnes** [comment]
@erlendsellie you must never be sorry for much needed prioritizing! You're doing this on "dugnad", and we're just happy that you got around to it. Already controlling Jacuzzi, heat pump, two heaters and heated floor in two rooms. Just in time for today's crazy electricity prices ;)
