### ISSUE TITLE
unit_of_measurement: NOK/kWh even if price in cent is chosen

### ISSUE THREAD

**Issue by ArveVM** [erlendsellie/priceanalyzer#42]
## Version of the custom_component

2.0-BETA

## Homeassistant version
2024.11.3

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
NO3 price in cent  - and it shows NOK/kWh as unit of measurement

but all in all - great to see a new version Erlend ;)
and happy to contribute on the trivial details "on my level"  ;)

## Debug log

```text

Add your logs here.

```

**Comment by ArveVM** [comment]
testa [2.0-beta2](https://github.com/erlendsellie/priceanalyzer/releases/tag/2.0-beta2) , får fortsatt NOK/kWh

Prøvde først kun redownload i beta2 i HACS, restart, og så Configure/Submit på eksisterande integrasjon (fra Beta) , men var NOK
Fjerna så integrasjonen så der ikkje var noken Priceanalyzers,, restarta og lag inn på nytt med følgande data (resten som default)

![image](https://github.com/user-attachments/assets/9aa3f289-ad89-48e8-b966-29bf980e40d3)

.. og får NOK/kWh

**Comment by erlendsellie** [comment]
Jepp, forrige fiks gjorde ingenting, og lukket derfor ikke issuen.

Slipper ny offisiell versjon nå, hvor det skal være fikset :-)
