### ISSUE TITLE
Change name of attribute for price current hour?

### ISSUE THREAD

**Issue by ArveVM** [erlendsellie/priceanalyzer#5]
Among the rich functionality of the Priceananalyzer is the ability to show in the near future the upcomming prices.

It would be nice to show the current price in the apex-chart, but unfortunately there is an issue with the attribute-naming, where priceanalyzer have attribute named 'value' for current price,, ant that "dont fly" with apex ???

It might just be me,, but I guess I'd report it and see what the expert say  ;)

Troubleshooting:
- looking at similar functionality in the Nordpool-integration,, where the attribute is named 'current_price', and that works just fine in Apex
- Priceanalyzer attributes like 'min', 'max', ' peak' and 'average' is working fine, just not the 'value'-attribute.

is it my config in Apex that is wrong?
or do I have to create another card displaying that particular data?
or can the value be added to a differently named attribute so Apex is not getting hickups?

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/96014323/191248650-3733c7da-4083-49ea-b7d8-dff04a0dde60.png">

**Comment by ArveVM** [comment]
naaahh,,,
rookie mistake  - but still not working :)
  - did check in devTools template:
{{states.sensor.priceanalyzer.attributes.current_hour.value}}    gives right value

So now that I (finally) know the syntax,, is there a way to get it into Apex directly?
or is the proper workaround to create a template-sensor with 'PriceAnalyzer_current_hour_value' ?

<img width="709" alt="image" src="https://user-images.githubusercontent.com/96014323/191348020-a00bb961-86e8-4376-a051-3396f98d0f9f.png">

**Comment by erlendsellie** [comment]
Woops, didn't see this Issue before now!
Did you figure it out, by any chance? I have not used this kind of header with ApexCharts, so i wouldn't know.
The attribute is correct though.

**Comment by ArveVM** [comment]
> Woops, didn't see this Issue before now! Did you figure it out, by any chance? I have not used this kind of header with ApexCharts, so i wouldn't know. The attribute is correct though.

Nope,,, but I guess it's an Apex-issue, and not Priceanalyzer (as you clearely agree ;)  )
-  workarounds as I see it:
    1. create template sensor and add that sensor to apex-chart header
    2. create vertical stack with other cards and entities above the Apex
