### ISSUE TITLE
Does additional_costs take into account the entire forecast?

### ISSUE THREAD

**Issue by jkaberg** [erlendsellie/priceanalyzer#7]
Hey @erlendsellie, while setting up Priceanlyzer an thought struck me. Does Priceanalyzer take into account the entire forecast, or only the current hour when setting additional_costs?

In my case I've set it to cover tariff costs, and it looks like this
```
  additional_costs: >-
    {% if now().weekday() in [5, 6] %}
        0.2839
    {% elif now().hour >= 6 and now().hour < 23 %}
        0.3626
    {% else %}
        0.2839
    {% endif %}
```

However my concern is that the additional cost is only computed for the current hour?

**Comment by erlendsellie** [comment]
Hi!
Additional costs are calculated for each hour for today and tomorrow, not just the current hour. 1.0 version ( In beta/prerelease at the moment) also fixes some issues with calculating the 10 and 5 cheapest hours when using additional_costs.

Setup using YAML is deprecated in 1.0, however, as i could not make YAML-support work while implementing support for editing an already configuring sensor, and fixing and issue when using multiple sensors.
 
The 1.0 version is maybe relased today, and is available as a beta if you select 'show beta versions' for Priceanalyzer in HACS.

**Comment by jkaberg** [comment]
Thanks for clearing that up, additional_cost seems very "here and now" centric when you look at it so had to ask 😄 Yeah I'll be upgrading shortly!

**Comment by erlendsellie** [comment]
Yeah, the 'date.now()'-part of it seems very 'here and now'. I had the same doubts when i started using the Nordpool-sensor.(which uses the same code)
